In [3]:
import numpy as np

# Câu 1: Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.full((3, 3), True)
print("arr:\n", arr)

arr:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


 Câu 2: Cho arr_1D = np.array([0 1 2 3 4 5 6 7 8]). Tạo array 2 chiều có kích thước 3x3 từ arr_1D, và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.

In [4]:
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("arr_2D sau khi đổi cột:\n", arr_2D)

arr_2D sau khi đổi cột:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [5]:

arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("arr_2D sau khi đổi dòng:\n", arr_2D)

arr_2D sau khi đổi dòng:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [6]:
# Câu 4: Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D.
arr_2D = arr_2D[::-1]
print("arr_2D sau khi đảo ngược dòng:\n", arr_2D)

# Câu 5: Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.
arr_2D = arr_2D[:, ::-1]
print("arr_2D sau khi đảo ngược cột:\n", arr_2D)

# Câu 6: Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), Kiểm tra trong array có giá trị rỗng không?
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()
print("arr_2D_null có giá trị rỗng:", has_nan)

# Câu 7: Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0.
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("arr_2D_null sau khi thay thế giá trị null:\n", arr_2D_null

SyntaxError: incomplete input (2569715816.py, line 16)